### ISSUE TITLE
Tool bar image icons

### ISSUE THREAD

**Issue by Ravinder-webonise** [brommko/SuperView#28]
Hello , I want to remove the tool bar titles and want to place the icons for the same. So please help me with this. How we can modify the toolbar with the icons.

Thanks

**Comment by brommko** [comment]
Hi,

You just need to make sure the name of the image in Assets.xcassets is the same as the title in customButtons. The app will try to show the image if exists and put the text if doesn't.

These are the reserved names: reload, share, back, forward and noads

Best regards

**Comment by Ravinder-webonise** [comment]
Thank you so much... it works like magic. And one more thing , how we can implement the selected tab icon functionality like other ios native apps does? Like selected icon is in selected colour and others are in fade in a colour. Will wait for your reply.
Thanks

**Comment by brommko** [comment]
Unfortunately, that is not the same component. Here we are using the native toolbar just to open a specific URL in the existing webview. 

For the tab bar, I would need a different implementation. A more similar implementation is the side menu. You can try it and maybe it will work for you.

**Comment by Ravinder-webonise** [comment]
Okay Thank you @brommko for your quick help.
