### ISSUE TITLE
Not able to Run Project on Xcode 13.0 , but working fine on Xcode 12.3

### ISSUE THREAD

**Issue by Ravinder-webonise** [brommko/SuperView#38]
Hey Team ,
                     i am facing issue while Running a code on xcode 13, but it is working fine on 12.3 . For your help i am going to attach screen shot of it. Please help me asap.

![Screenshot 2021-12-23 at 5 37 11 PM](https://user-images.githubusercontent.com/83577894/147238257-880bd1e4-e69b-4ff3-9625-d2873b63a132.png)

  Thanks

**Comment by brommko** [comment]
Hi,

You can use the latest version of Xcode 13.2, which is ok. Just make sure to run the **./run.sh** script which will install all the pods and open the xcworkspace file, the white icon. 

When the project opens, you can additionally clean the project with CMD + SHIFT + K and then run with CMD + R.

Best

**Comment by Ravinder-webonise** [comment]
ok Thanks
