### ISSUE TITLE
How to change colour of Side Menu items and top Navigation header Title colour

### ISSUE THREAD

**Issue by Ravinder-webonise** [brommko/SuperView#39]
Hi Team How i can change colour of side menu option title colours , and also top navigation title colour in your latest SDK.
For reference attaching screenshot , by default it is showing in black colour.
Help me out in this.
Thanks Bro
![Screenshot 2021-12-23 at 7 22 37 PM](https://user-images.githubusercontent.com/83577894/147249811-8c22f38d-4a81-41ac-9693-03f8f8a8d92f.png)
.

**Comment by brommko** [comment]
Hi,

You need ti open the project with Xcode and on the left side there is an Asset file. Select it and you can play with colors in there.

Best

**Comment by Ravinder-webonise** [comment]
Hy Thank you so much.
Yes it works for me.
