### ISSUE TITLE
App is running fine while Running from Xcode but Not crashing without Xcode

### ISSUE THREAD

**Issue by Ravinder-webonise** [brommko/SuperView#41]
Hey Team.  
                    i am facing issue with your latest code , i am able to Run my app while using Xcode Launch button. There is no issue using Xcode Run Button. But when ever i tired to run my existing Build from current Simulator (Not from Run button of Xcode) then app crashed just after splash. Please help me out. Also same thing happened on real devices too.
 My tools specifications:-
 Xcode 13.0
 iOS version 15.0
 Help me out guys.
 Thanks

**Comment by brommko** [comment]
Hi,

Can you run the app again from Xcode and send me the log? There has to be something to indicate what could be the problem. This sounds like a permission issue, you probably need to put some Privacy in Info.plist file.

Best regards

**Comment by Ravinder-webonise** [comment]
Hey These are the logs statements when ever i tried to launch the app from Xcode Run button.


2022-02-08 19:57:30.652186+0530 App[6616:93637] Writing analzed variants.
2022-02-08 19:57:30.851067+0530 App[6616:93637] Writing analzed variants.
2022-02-08 19:57:30.896721+0530 App[6616:93637] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600000157bb0 h=--& v=--& _UIToolbarContentView:0x13e511af0.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000012d9f0 H:|-(0)-[_UIButtonBarStackView:0x13e513a20]   (active, names: '|':_UIToolbarContentView:0x13e511af0 )>",
    "<NSLayoutConstraint:0x60000012da40 H:[_UIButtonBarStackView:0x13e513a20]-(0)-|   (active, names: '|':_UIToolbarContentView:0x13e511af0 )>",
    "<NSLayoutConstraint:0x6000001553b0 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x13e73b8d0]   (active, names: '|':_UIButtonBarButton:0x13e73b6f0 )>",
    "<NSLayoutConstraint:0x600000155860 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x13e73c600]   (active, names: '|':_UIButtonBarButton:0x13e73c420 )>",
    "<NSLayoutConstraint:0x600000155d10 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x13e73d050]   (active, names: '|':_UIButtonBarButton:0x13e73ce70 )>",
    "<NSLayoutConstraint:0x600000156210 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x13e73daa0]   (active, names: '|':_UIButtonBarButton:0x13e73d8c0 )>",
    "<NSLayoutConstraint:0x600000155400 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73b8d0]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73b6f0 )>",
    "<NSLayoutConstraint:0x6000001558b0 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73c600]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73c420 )>",
    "<NSLayoutConstraint:0x600000155d60 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73d050]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73ce70 )>",
    "<NSLayoutConstraint:0x600000156260 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73daa0]-(0)-|   (active, names: '|':_UIButtonBarButton:0x13e73d8c0 )>",
    "<NSLayoutConstraint:0x600000156c60 'UISV-canvas-connection' UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'.leading == UIView:0x13e73b380.leading   (active)>",
    "<NSLayoutConstraint:0x600000156cb0 'UISV-canvas-connection' UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'.trailing == UIView:0x13e73e1a0.trailing   (active)>",
    "<NSLayoutConstraint:0x600000156d00 'UISV-spacing' H:[UIView:0x13e73b380]-(0)-[_UIButtonBarButton:0x13e73b6f0]   (active)>",
    "<NSLayoutConstraint:0x600000156d50 'UISV-spacing' H:[_UIButtonBarButton:0x13e73b6f0]-(0)-[UIView:0x13e73c2b0]   (active)>",
    "<NSLayoutConstraint:0x600000156da0 'UISV-spacing' H:[UIView:0x13e73c2b0]-(0)-[_UIButtonBarButton:0x13e73c420]   (active)>",
    "<NSLayoutConstraint:0x600000156df0 'UISV-spacing' H:[_UIButtonBarButton:0x13e73c420]-(0)-[UIView:0x13e73cd00]   (active)>",
    "<NSLayoutConstraint:0x600000156e40 'UISV-spacing' H:[UIView:0x13e73cd00]-(0)-[_UIButtonBarButton:0x13e73ce70]   (active)>",
    "<NSLayoutConstraint:0x600000156e90 'UISV-spacing' H:[_UIButtonBarButton:0x13e73ce70]-(0)-[UIView:0x13e73d750]   (active)>",
    "<NSLayoutConstraint:0x600000156ee0 'UISV-spacing' H:[UIView:0x13e73d750]-(0)-[_UIButtonBarButton:0x13e73d8c0]   (active)>",
    "<NSLayoutConstraint:0x600000156f30 'UISV-spacing' H:[_UIButtonBarButton:0x13e73d8c0]-(0)-[UIView:0x13e73e1a0]   (active)>",
    "<NSLayoutConstraint:0x60000012d860 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x13e513a20 )>",
    "<NSLayoutConstraint:0x60000012d900 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x13e513a20 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000155d60 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73d050]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73ce70 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-02-08 19:57:30.897606+0530 App[6616:93637] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600000157bb0 h=--& v=--& _UIToolbarContentView:0x13e511af0.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000012d9f0 H:|-(0)-[_UIButtonBarStackView:0x13e513a20]   (active, names: '|':_UIToolbarContentView:0x13e511af0 )>",
    "<NSLayoutConstraint:0x60000012da40 H:[_UIButtonBarStackView:0x13e513a20]-(0)-|   (active, names: '|':_UIToolbarContentView:0x13e511af0 )>",
    "<NSLayoutConstraint:0x6000001553b0 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x13e73b8d0]   (active, names: '|':_UIButtonBarButton:0x13e73b6f0 )>",
    "<NSLayoutConstraint:0x600000155860 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x13e73c600]   (active, names: '|':_UIButtonBarButton:0x13e73c420 )>",
    "<NSLayoutConstraint:0x600000156210 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x13e73daa0]   (active, names: '|':_UIButtonBarButton:0x13e73d8c0 )>",
    "<NSLayoutConstraint:0x600000155400 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73b8d0]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73b6f0 )>",
    "<NSLayoutConstraint:0x6000001558b0 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73c600]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x13e73c420 )>",
    "<NSLayoutConstraint:0x600000156260 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x13e73daa0]-(0)-|   (active, names: '|':_UIButtonBarButton:0x13e73d8c0 )>",
    "<NSLayoutConstraint:0x600000156c60 'UISV-canvas-connection' UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'.leading == UIView:0x13e73b380.leading   (active)>",
    "<NSLayoutConstraint:0x600000156cb0 'UISV-canvas-connection' UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'.trailing == UIView:0x13e73e1a0.trailing   (active)>",
    "<NSLayoutConstraint:0x600000156d00 'UISV-spacing' H:[UIView:0x13e73b380]-(0)-[_UIButtonBarButton:0x13e73b6f0]   (active)>",
    "<NSLayoutConstraint:0x600000156d50 'UISV-spacing' H:[_UIButtonBarButton:0x13e73b6f0]-(0)-[UIView:0x13e73c2b0]   (active)>",
    "<NSLayoutConstraint:0x600000156da0 'UISV-spacing' H:[UIView:0x13e73c2b0]-(0)-[_UIButtonBarButton:0x13e73c420]   (active)>",
    "<NSLayoutConstraint:0x600000156df0 'UISV-spacing' H:[_UIButtonBarButton:0x13e73c420]-(0)-[UIView:0x13e73cd00]   (active)>",
    "<NSLayoutConstraint:0x600000156e40 'UISV-spacing' H:[UIView:0x13e73cd00]-(0)-[_UIButtonBarButton:0x13e73ce70]   (active)>",
    "<NSLayoutConstraint:0x600000156e90 'UISV-spacing' H:[_UIButtonBarButton:0x13e73ce70]-(0)-[UIView:0x13e73d750]   (active)>",
    "<NSLayoutConstraint:0x600000156ee0 'UISV-spacing' H:[UIView:0x13e73d750]-(0)-[_UIButtonBarButton:0x13e73d8c0]   (active)>",
    "<NSLayoutConstraint:0x600000156f30 'UISV-spacing' H:[_UIButtonBarButton:0x13e73d8c0]-(0)-[UIView:0x13e73e1a0]   (active)>",
    "<NSLayoutConstraint:0x60000012d860 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600001b6a680'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x13e513a20 )>",
    "<NSLayoutConstraint:0x60000012d900 'UIView-rightMargin-guide-constraint'

**Comment by brommko** [comment]
Nothing special there. Did you try the latest version?

pod "SuperView/Core", :git => 'https://github.com/brommko/SuperView.git', :tag => '1.3.3'

Also try to set useNetworkCheck to 0 in the Config.plist file.

**Comment by brommko** [comment]
I will close this issue for now.
